include ../Makefile.ops

.PHONY:all
all: group.o groupMsg.o groupManager.o

group.o: group.cpp
	$(CXX) group.cpp $(CXXFLAG)
groupMsg.o: groupMsg.cpp
	$(CXX) groupMsg.cpp $(CXXFLAG)
groupManager.o: groupManager.cpp
	$(CXX) groupManager.cpp $(CXXFLAG)
